version: '3'

services:
  web:
    image: node:lts-alpine3.18
    volumes:
      - ./frontend/app:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: sh -c "npm install && npm start"
    depends_on:
      - api
  api:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "5555:5555"
    command: python /app/app.py